# Generated by Django 5.2.1 on 2025-05-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_micronutrient', models.BooleanField(default=False)),
                ('meassure_unit', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Nutrient',
                'verbose_name_plural': 'Nutrients',
            },
        ),
    ]
