from rest_framework import serializers
from .models import Nutrient


class NutrientDataSerializer(serializers.Serializer):
    food_group = serializers.CharField(required=True, max_length=50)
    food_name = serializers.CharField(required=True, max_length=50)
    quantity = serializers.IntegerField(default=0)
    is_fortified_with = serializers.IntegerField(default=0)
    enercj = serializers.IntegerField(default=0)
    enercc = serializers.IntegerField(default=0)
    water = serializers.IntegerField(default=0)
    prot = serializers.IntegerField(default=0)
    protpl = serializers.IntegerField(default=0)
    protan = serializers.IntegerField(default=0)
    nt = serializers.IntegerField(default=0)
    trp = serializers.IntegerField(default=0)
    fat = serializers.IntegerField(default=0)
    facid = serializers.IntegerField(default=0)
    fasat = serializers.IntegerField(default=0)
    famscis = serializers.IntegerField(default=0)
    fapu = serializers.IntegerField(default=0)
    fapun3 = serializers.IntegerField(default=0)
    fapun6 = serializers.IntegerField(default=0)
    fatrs = serializers.IntegerField(default=0)
    cho = serializers.IntegerField(default=0)
    sugar = serializers.IntegerField(default=0)
    starch = serializers.IntegerField(default=0)
    polyl = serializers.IntegerField(default=0)
    fibt = serializers.IntegerField(default=0)
    alc = serializers.IntegerField(default=0)
    oa = serializers.IntegerField(default=0)
    ash = serializers.IntegerField(default=0)
    chorl = serializers.IntegerField(default=0)
    na = serializers.IntegerField(default=0)
    k = serializers.IntegerField(default=0)
    ca = serializers.IntegerField(default=0)
    p = serializers.IntegerField(default=0)
    mg = serializers.IntegerField(default=0)
    fe = serializers.IntegerField(default=0)
    haem = serializers.IntegerField(default=0)
    nhaem = serializers.IntegerField(default=0)
    cu = serializers.IntegerField(default=0)
    se = serializers.IntegerField(default=0)
    zn = serializers.IntegerField(default=0)
    id = serializers.IntegerField(default=0)
    vita_rae = serializers.IntegerField(default=0)
    vita_re = serializers.IntegerField(default=0)
    retol = serializers.IntegerField(default=0)
    cartbtot = serializers.IntegerField(default=0)
    carta = serializers.IntegerField(default=0)
    lutn = serializers.IntegerField(default=0)
    zea = serializers.IntegerField(default=0)
    crypxb = serializers.IntegerField(default=0)
    lycpn = serializers.IntegerField(default=0)
    vitd = serializers.IntegerField(default=0)
    chocaloh = serializers.IntegerField(default=0)
    chocal = serializers.IntegerField(default=0)
    ergcal = serializers.IntegerField(default=0)
    vite = serializers.IntegerField(default=0)
    tocpha = serializers.IntegerField(default=0)
    tocphb = serializers.IntegerField(default=0)
    tocphd = serializers.IntegerField(default=0)
    tocphg = serializers.IntegerField(default=0)
    vitk = serializers.IntegerField(default=0)
    vitk1 = serializers.IntegerField(default=0)
    vitk2 = serializers.IntegerField(default=0)
    thia = serializers.IntegerField(default=0)
    ribf = serializers.IntegerField(default=0)
    vitb6 = serializers.IntegerField(default=0)
    vitb12 = serializers.IntegerField(default=0)
    niaeq = serializers.IntegerField(default=0)
    nia = serializers.IntegerField(default=0)
    fol = serializers.IntegerField(default=0)
    folfd = serializers.IntegerField(default=0)
    folac = serializers.IntegerField(default=0)
    vitc = serializers.IntegerField(default=0)
    fasatxr = serializers.IntegerField(default=0)
    famscxr = serializers.IntegerField(default=0)
    fapuxr = serializers.IntegerField(default=0)
    famstxr = serializers.IntegerField(default=0)
    faun = serializers.IntegerField(default=0)


class NutrientDataSerializer(serializers.ModelSerializer):
    class Meta:
        model = Nutrient
        fields = "__all__"
