on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  verify_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          # If you install into a venv in the workspace, cache it too.
          # .venv/  # Example if you create a .venv in the root
        # Corrected path for hashFiles
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('nutrient_tracker/config/requirements/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Corrected path to requirements.txt
        pip install -r nutrient_tracker/config/requirements/requirements.txt
        pip install psycopg2-binary # This is fine as is
    - name: Basic Django sanity check
      # Assuming manage.py is at nutrient_tracker/manage.py
      run: python nutrient_tracker/manage.py check
      # OR, if you prefer to set a working directory for Django commands:
      # working-directory: ./nutrient_tracker
      # run: python manage.py check
    # Future test section (commented out)
    # - name: Run all tests
    #   # Assuming manage.py is at nutrient_tracker/manage.py
    #   run: |
    #     python nutrient_tracker/manage.py test \
    #       apps.food_data.tests \
    #       apps.nutrient_data.tests \
    #       apps.tracker_data.tests \
    #       apps.user_info.tests \
    #       --noinput